FROM openanalytics/shinyproxy:latest

WORKDIR /opt/shinyproxy

USER root
# Installing R and all the dependencies :
RUN apt-get update \
    && apt-get install -y wget dirmngr gnupg apt-transport-https ca-certificates software-properties-common libcurl4-openssl-dev libssl-dev build-essential  libxml2-dev pandoc\
    # libcurl4-gnutls-dev
    && add-apt-repository -y "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/" \ 
    && wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc \
    && apt-get install -y r-base \
    && apt-get install -y r-base-dev

RUN R -e 'install.packages("shiny",dependencies=TRUE)' \
    && R -e 'install.packages("reshape2",dependencies=TRUE)' \
    && R -e 'install.packages("ggplot2",dependencies=TRUE)' \
    && R -e 'install.packages("dplyr",dependencies=TRUE)' \
    && R -e 'install.packages("ggrepel",dependencies=TRUE)' \
    && R -e 'install.packages("ggthemes",dependencies=TRUE)' \
    && R -e 'install.packages("shinythemes",dependencies=TRUE)' \
    && R -e 'install.packages("optparse",dependencies=TRUE)' \
    && R -e 'install.packages("plotly",dependencies=TRUE)' \
    && R -e 'install.packages("flexdashboard",dependencies=TRUE)' \
    && R -e 'install.packages("htmltools",dependencies=TRUE)' \
    && R -e 'install.packages("DT",dependencies=TRUE)' \
    && R -e 'install.packages("xml2",dependencies=TRUE)' \
    && R -e 'install.packages("devtools",dependencies=TRUE)' \
    && R -e 'devtools::install_github("rstudio/crosstalk")' \
    && R -e 'install.packages("rmarkdown",dependencies=TRUE)' \ 
    && R -e 'install.packages("downloadthis",dependencies=TRUE)'

ENV VERSION="2.6.1"


RUN wget https://www.shinyproxy.io/downloads/shinyproxy_${VERSION}_amd64.deb \
    && apt install -y ./shinyproxy_${VERSION}_amd64.deb \
    && rm shinyproxy_${VERSION}_amd64.deb

USER shinyproxy